### ISSUE TITLE
Support for sarasa-gothic-ttc-unhinted

### ISSUE THREAD

**Issue by b4imetu** [matthewjberger/scoop-nerd-fonts#182]
When I install the Sarasa Gothic package with *Scoop*, the font takes up over 10G of my storage, which is very storage-intensive. I might as well install a few common Sarasa Gothic fonts manually.

Support for [sarasa-gothic-ttc-unhinted-$version$.7z](https://github.com/be5invis/Sarasa-Gothic/releases/download/v0.36.5/sarasa-gothic-ttc-unhinted-0.36.5.7z)

.ttc is much smaller than .ttf, and unhindered is smaller than hinted with almost no effect on the display

**Comment by issaclin32** [comment]
You are right.
The ttc version takes way less space (730 MB) compared to ttf version (10.8 GB), and even [region-specific ttf](https://github.com/matthewjberger/scoop-nerd-fonts/pull/30) takes 1.8GB. We should probably add `notes` that directs user to install the **ttc version** when they are installing the ttf one.

**Asking for you opinion about this: @jonz94


> Support for [sarasa-gothic-ttc-unhinted-$version$.7z](https://github.com/be5invis/Sarasa-Gothic/releases/download/v0.36.5/sarasa-gothic-ttc-unhinted-0.36.5.7z)

Will add it later.

**Comment by jonz94** [comment]
> We should probably add `notes` that directs user to install the **ttc version** when they are installing the ttf one.

I generally +1 for this.

I think only if you have specific use case, otherwise installing the ttc version is better as it takes less space with no drawbacks.

The only edge case I found is that ttc format [may not supported in **Windows 7**](https://superuser.com/questions/114603/how-to-install-os-x-ttc-font-on-windows-error-ttc-does-not-appear-to-be-a), but I think most of the scoop users are using Windows 10/11 nowadays. 🤣

**Comment by b4imetu** [comment]
Thank you for taking my issue, it helps a lot!
Thank you for your contribution to the CJK font community.
@issaclin32 @jonz94
