### ISSUE TITLE
Question about Cascadia Mono

### ISSUE THREAD

**Issue by mattalexx** [matthewjberger/scoop-nerd-fonts#216]
I'm wondering, is there any reason you didn't include Cascadia Mono versions of [CascadiaCode-NF] and [CascadiaCode-NF-Mono]?

For the uninformed, Cascadia Mono is Cascadia Code without ligatures, and font ligatures do my head in. I suppose I've stared at `>=` enough that `≥` is what confuses me at this point.

If indeed there's no reason beyond a lack of demand, then maybe I'll make an attempt at writing a recipe if I find some free time.

[CascadiaCode-NF]: https://github.com/matthewjberger/scoop-nerd-fonts/blob/master/bucket/CascadiaCode-NF.json
[CascadiaCode-NF-Mono]: https://github.com/matthewjberger/scoop-nerd-fonts/blob/master/bucket/CascadiaCode-NF-Mono.json

**Comment by jonz94** [comment]
Hi, @mattalexx 

Currently, we do not have the **Cascadia Mono** version because upstream https://github.com/ryanoasis/nerd-fonts repository does not have Cascadia Mono patched font. (see https://github.com/ryanoasis/nerd-fonts/issues/520)

We rely on the upstream nerd-fotns repository put the patched font in their [release page](https://github.com/ryanoasis/nerd-fonts/releases),
(because what the font installer in this repository do is download the fonts from their release page)
until the upstream release the Cascadia Mono patched font,
I think there is not much we can do for now.

Maybe you can try `Delugia-Mono-Nerd-Font` from https://github.com/adam7/delugia-code. It is generated from Cascadia Mono with [some little tweaks](https://github.com/adam7/delugia-code#how-is-delugia-special).

**Comment by mattalexx** [comment]
Oh I get it. I'll check out delugia code, Thanks.

**Comment by Finii** [comment]
Delugia just got the Nerd Fonts 2.3.3 update ;)

**Comment by jonz94** [comment]
Hi,

I just add `CascadiaMono-NF`, `CascadiaMono-NF-Mono`, and `CascadiaMono-NF-Propo`.
Now, we can use the following commands to install them:

```shell
scoop update

scoop install CascadiaMono-NF
scoop install CascadiaMono-NF-Mono
scoop install CascadiaMono-NF-Propo
```
