### ISSUE TITLE
FiraCode installer script fails 

### ISSUE THREAD

**Issue by OdinTech3** [matthewjberger/scoop-nerd-fonts#70]
![image](https://user-images.githubusercontent.com/14257815/79632386-d298e100-812c-11ea-8928-fbed9caf1884.png)

It looks like it is not able to copy the ttf files into the C:\Windows\Fonts directory.

**Comment by TheZoker** [comment]
Mine looks like this:
![Screenshot_2020 04 18_15h33m20s_001_](https://user-images.githubusercontent.com/1368405/79639137-fa6a6200-8189-11ea-99f7-69d41defcdae.png)

**Comment by matthewjberger** [comment]
If the `Copy-Item` cmdlet is failing with an error saying `The requested operation cannot be performed on a file with a user-mapped section open`, it's because another process is locking that directory. It can be tricky to pin down what is locking the folder locally but unfortunately it cannot be fixed in the manifest or in scoop itself

**Comment by ueberBrot** [comment]
> **Edit:** Fixed it by using `sudo scoop install FiraCode` (after installing sudo via `scoop install sudo`)

This is the intended use as stated in the [`README` ](https://github.com/matthewjberger/scoop-nerd-fonts/blob/master/README.md). 

> **Note: Admin rights are required to install these fonts, because their installers modify the registry. Additionally, restarting your computer after uninstalling a font is necessary for the font to be fully removed.**

If I'm not mistaken  you need admin privileges to install anything on `C` drive except its in you user folder. That's why you need to elevate PowerShell.
